[workspace]
members = [
    "navigation_compass_solver",
    "museum_solver",
    "bin_by_img",
    "tools_wasm",
    "video_in_waveform",
    "video_batch_compresser",
    "gi_rhythm",
    "gi_teleport_detect",
    "img_blender",
    "pua_codec",
    "aeroplane_chess_solver",
    "audio_mirror",
    "live_health_bar",
]
resolver = "2"

[profile.dev_fast]
inherits = "dev"
opt-level = 1

[profile.dev_fast.package."*"]
opt-level = 3
