[package]
name = "bin_by_img"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
image = "0.24.7"
itertools = "0.11.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
